### PR TITLE
Misc. build system and source build fixes

### PR DESCRIPTION
**Pull request by troglobit**

### CODE REVIEW

**Comment by troglobit** [comment]
Maybe you'd prefer converting to GNU configure & build system (autoconf + automake) instead?

**Comment by julienblitte** [comment]
In src/ssdp.c, line 42
You must substract strlen(st_list) in strncat to avoid memory leak.
Strangely, strncat is taking as 3rd argument, the maximum number of char to add, not total size of destination.

**Comment by troglobit** [comment]
Good catch, here's a hopefully better version.

**Comment by julienblitte** [comment]
Thanks! :-)

**Pull request merged**
